# Generated by Django 3.1.3 on 2020-11-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bibld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bib', models.CharField(max_length=50, verbose_name='Название')),
                ('anons_bib', models.CharField(max_length=250, verbose_name='Анонс')),
                ('full_text_bib', models.TextField(verbose_name='Описание')),
                ('date_bib', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
